[build]
  publish = "."
  command = "node scripts/build-env.js && echo 'Build complete with environment variables processed'"

[[redirects]]
  from = "/obrigado"
  to = "/obrigado.html"
  status = 200

[[redirects]]
  from = "/back-redirect"
  to = "/back-redirect.html"
  status = 200

[[redirects]]
  from = "/politica-de-privacidade"
  to = "/politica-de-privacidade.html"
  status = 200

[[redirects]]
  from = "/termos-de-uso"
  to = "/termos-de-uso.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"